### ISSUE TITLE
Inserir documentação do docker no readme

### ISSUE THREAD

**Issue by ludimila** [prefeiturasp/SME-PratoAberto-API#20]
A aplicação já usa docker/docker-compose
Mas não tem documentação do passo a passo para subir a aplicação com o docker.

**Comment by edsoncelio** [comment]
Olá @ludimila , estou entendendo o projeto pra contribuir nessa parte, e ficou uma dúvida: porque não executar a API dentro do `Dockerfile` (usando `CMD`) e sim no `docker-compose`? 
Ficaria bem modulado, dando a opção de usar o `Dockerfile` separado.
obs: foi só uma dúvida que ficou, pode ser que exista um motivo em específico para estar assim :)

**Comment by Guilhermeslucas** [comment]
Olá! Parabéns pelo projeto e pelas contribuições! Vi que a documentação sobre Docker que o @edsoncelio fala sobre o compose, mas ainda não contempla o docker standalone, com um container para o banco e outro com a aplicação, e na documentação oficial, é esperado um container mongo. Posso tocar essa documentação? Abraços!

**Comment by ludimila** [comment]
Pode sim @Guilhermeslucas
