### ISSUE TITLE
Atualizar docker-compose para criar a pasta db_dump

### ISSUE THREAD

**Issue by ludimila** [prefeiturasp/SME-PratoAberto-API#21]
Dentro da pasta mongo-seed uma pasta chamada db_dump e os  arquivos  ./ bson e  .json devem ficar dentro desta pasta.

**Comment by fdiasdev** [comment]
@ludimila olhando o projeto essa issue me pareceu quase done. Os arquivos ja estão em `db_dump/`, mas existe os mesmo duplicados em root. Ainda é pertinente ? 

No meu entendimento, talvez uma limpeza seria interessante e um pequeno ajusto no `Dockerfile`

Posso abrir um PR ?

**Comment by ludimila** [comment]
sim @fdiasdev
