### ISSUE TITLE
Ignorar acentos na busca por escolas

### ISSUE THREAD

**Issue by bplmp** [prefeiturasp/SME-PratoAberto-API#4]
# Problema:
Busca de escolas por nome não ignora acentos.

# Possível solução 1:
Substituir query na api de `$regex` para `$text`, por exemplo:

    query['nome'] = { '$text': { '$search': nome, '$language': 'pt', '$caseSensitive': False, '$diacriticSensitive': False } }

**Atenção, isso só funciona no Mongo versão 3.2 ou maior. Não testei os resultados. Referência: https://docs.mongodb.com/manual/reference/operator/query/text/**

# Possível solução 2:
Remover acentos do texto inputado pelo usuário, supondo que na base de dados nunca haverá acentos. Exemplo:

    accented_string = u'Málaga'
    # accented_string is of type 'unicode'
    import unidecode
    unaccented_string = unidecode.unidecode(accented_string)
    # unaccented_string contains 'Malaga'and is of type 'str'

Referência: https://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-in-a-python-unicode-string

**Comment by alvarojoao** [comment]
Hello,
I would love to help you with this issue; 
I believe I already did some work that might help you;

-------

Falo português;

**Comment by bplmp** [comment]
Oi @alvarojoao, tudo bem? Quer fazer um pull request? Ou dar uma ideia da sua solução?

**Comment by silveiraluiza** [comment]
já tem solução ou gente trabalhando nisso? o $text do mongo só vai dar certo se procurar por uma palavra chave, não uma busca textual propriamente dita, então eu usaria a segunda solução.
