### ISSUE TITLE
Erro de faixa etária 

### ISSUE THREAD

**Issue by ludimila** [prefeiturasp/SME-PratoAberto-API#6]
De – Para de terceirizada – faixa I- 2 a 6 anos está aparecendo no site como “ 4 a 6 anos”

![image](https://user-images.githubusercontent.com/1562636/44608213-58824e80-a7c9-11e8-998b-cc761c78e061.png)

**Comment by jcert** [comment]
Esse erro ainda está acontecendo? Busquei no repositório e só achei a string "4 a 6 anos" para a categoria G.
